lab7/myimgur/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign-up', views.SignUpView.as_view(), name='signup'),
]

lab7/myimgur/app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:image_id>/', views.detail, name='detail'),
    path('<int:image_id>/comment', views.comment, name='comment'),
    path('approve/<int:comment_id>', views.approve_comment, name='approve_comment'),
    path('delete/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('like_comment/<int:comment_id>', views.like_comment, name='like_comment'),
    path('new', views.create_image , name='create_image'),
    path('<int:image_id>/edit', views.update_image, name="update_image"),
    path('<int:image_id>/delete', views.delete_image, name="delete_image"),
    path('<int:image_id>/upvote', views.upvote, name='upvote'),
    path('<int:image_id>/downvote', views.downvote, name='downvote'),
    path('accounts/<int:user_id>', views.account, name='account'),
]

lab7/myimgur/imgur/urls.py
from django.contrib import admin
from django.urls import include,path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('images/', include('app.urls')),
    path('', views.index, name='index'), 
]

lab7/myimgur/app/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>My Really Lame Imgur</title>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>

    {% block extrahead %}
    {% endblock %}

    <link rel="stylesheet" type="text/css" href="{% static 'app/css/app.css' %}">
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">My Really Lame Imgur</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">Hi {{user.username}}</a>
            </li>
            {%if user.is_superuser%}
            <li class="nav-item">
              <a class="nav-link" href="/admin">Admin</a>
            </li>
            {%endif%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout'%}">Logout</a>
            </li>
            {%else%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup'%}">Sign up</a>
            </li>
            {% endif %}

          </ul>
        </div>
      </nav>

    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron">
            <div class="container">
              <h1 class="display-4">My Really Lame Imgur</h1>
              <p class="lead">Your one stop place for posting your lamest images!</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

lab7/myimgur/app/templates/app/create_image.html
{% extends 'app/base.html' %} 
{% block extrahead %} 
{{form.media}} 
{% endblock extrahead %} 
{% block content %}
<div class="row">
  <div class="col-md-12">
    {% if action == "create"%}
    <h2 class="text-center">Submit new image</h2>
    {% else %}
    <h2 class="text-center">Edit image</h2>
    {% endif %}
  </div>
</div>
<form accept-charset="utf-8" method="post">
  {% csrf_token %} {% include 'includes/form.html' with form=form %}
  <div class="row">
    <div class="col-md-8 mx-auto">
      <input class="btn btn-primary" type="submit" value="Submit" />
    </div>
  </div>
</form>
{% endblock %}

lab7/myimgur/app/templates/app/detail.html
{% extends 'app/base.html' %} 
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="date">{{ image.pub_date }} Published by: <a href="{%url 'app:account' image.user.id%}">{{image.user.username}}</a></div>
      {% if request.user.is_authenticated %}
      {%include "includes/vote_buttons.html" with image=image vote=vote%}
      {% else %}
      Score: {{image.vote_score}}
      {% endif %}
      <h2>{{ image.title }}</h2>
      <img class="app-fit" src="{{image.url}}" alt="" />
    </div>
    <div class="col-md-6">
      <h3>Description</h3>
      <p>{{ image.description|linebreaksbr }}</p>
      <h3>Comments</h3>
      {% for comment,like in comments_with_likes %}
      <div class="border comment">
        <p class="red">Author: <a href="{%url 'app:account' comment.user.id%}">{{ comment.author }}</a> ({{comment.created_at}})</p>
        <p class="secondary">{{ comment.text }}</p>

        {% if comment.approved == False %}
        {%if request.user.is_superuser%}
        {% include 'includes/delete_comment_link.html' with comment=comment %}
        {%endif%}
          <form 
            action = "{%url 'app:approve_comment' comment.id%}"
            method="post">
            {%csrf_token%}
            <input type="submit" value="Approve" class="btn btn-success"/>
          </form>
        {%endif%}
      

        {%if comment.approved == True and request.user.is_authenticated%}
        {% if request.user.is_superuser or comment.user == request.user%}
        {% include 'includes/delete_comment_link.html' with comment=comment %}
        {%endif%}
        {% include "includes/like_button.html" with comment=comment like=like%}
        {%else%}
        Likes: {{comment.total_likes}}
        {%endif%}

      </div>
      {% endfor %}
      {% if request.user.is_authenticated %}
      <h2>Post a comment</h2>
      {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
      {% endif %}

      <form
        action="{% url 'app:comment' image.id %}"
        method="post"
        class="border"
      >
        {% csrf_token %} {%include "includes/form.html" with form=form%}
        <input
          type="submit"
          value="Post Comment"
          class="btn btn-lg btn-primary btn-block"
        />
      </form>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

lab7/myimgur/app/templates/app/index.html
{% extends 'app/base.html' %} 
{% block content %}
{% if request.user.is_authenticated %}
<div class="row">
  <div class="col-md-10">
    <p><a href="{% url 'app:create_image' %}">Submit new image.</a></p>
  </div>
</div>
{% endif %}
{% for image,vote in images_with_votes %}
<div class="row">
  <div class="col-md-2">
    <img class="app-fit" src="{{image.url}}" alt="" />
  </div>
  <div class="col-md-10">
    <div class="date">
      <p class="red">
        Published by: <a href="{% url 'app:account' image.user.id%}">{{image.user.username}}</a>, {{ image.pub_date }};
        {%if request.user.is_authenticated and request.user.is_superuser or image.user == request.user%}
        <a href="{% url 'app:update_image' image.id %}">Edit</a> | 
        {% include 'includes/delete_image_link.html' with image=image %}
        {%endif%}
      </p>  
    </div>
    {% if request.user.is_authenticated %}
    {%include "includes/vote_buttons.html" with image=image vote=vote%}
    {%else%}
    Score: {{image.vote_score}}
    {% endif %}
    <h2><a href="{% url 'app:detail' image.id %}">{{ image.title }}</a></h2>
    <p>{{ image.description|linebreaksbr }}</p>
  </div>
</div>
{% endfor %} {% endblock %}

lab7/myimgur/app/templates/app/profile.html
{% extends 'app/profile_base.html' %}

{%block profile_username%}
<h1>Profile username: {{profile_username}}</h1>
{%endblock%}

{% block content %}
<h3>Posts</h3>
{% for image,vote in images_with_votes %}
<div class="row">
  <div class="col-md-4">
    <img class="app-fit" src="{{image.url}}" alt="" />
  </div>
  <div class="col-md-8">
    <div class="date">
      <p class="red">
        Published by: <a href="{% url 'app:account' image.user.id%}">{{image.user.username}}</a>, {{ image.pub_date }};
        {%if request.user.is_authenticated and request.user.is_superuser or image.user == request.user%}
        <a href="{% url 'app:update_image' image.id %}">Edit</a> | 
        {% include 'includes/delete_image_link.html' with image=image %}
        {%endif%}
      </p>  
    </div>
    {% if request.user.is_authenticated %}
    {%include "includes/vote_buttons.html" with image=image vote=vote%}
    {%else%}
    Score: {{image.vote_score}}
    {% endif %}
    <h2><a href="{% url 'app:detail' image.id %}">{{ image.title }}</a></h2>
    <p>{{ image.description|linebreaksbr }}</p>
  </div>
</div>
{% endfor %} 
{% endblock %}

{%block account_comments%}
<h3>Comments</h3>
      {% for comment,like in comments_with_likes %}
      <div class="border comment">
        <p class="red">Author: <a href="{%url 'app:account' comment.user.id%}">{{ comment.author }}</a> ({{comment.created_at}}),
            On post: <a href="{%url 'app:detail' comment.image.id%}">{{comment.image.title}}</a>
        </p>
        <p class="secondary">{{ comment.text }}</p>

        {% if comment.approved == False %}
        {%if request.user.is_superuser%}
        {% include 'includes/delete_comment_link.html' with comment=comment %}
        {%endif%}
          <form 
            action = "{%url 'app:approve_comment' comment.id%}"
            method="post">
            {%csrf_token%}
            <input type="submit" value="Approve" class="btn btn-success"/>
          </form>
        {%endif%}
      

        {%if comment.approved == True and request.user.is_authenticated%}
        {% if request.user.is_superuser or comment.user == request.user%}
        {% include 'includes/delete_comment_link.html' with comment=comment %}
        {%endif%}
        {% include "includes/like_button.html" with comment=comment like=like%}
        {%else%}
        Likes: {{comment.total_likes}}
        {%endif%}

      </div>
      {% endfor %}
{%endblock%}

lab7/myimgur/app/templates/app/profile_base.html
{% load static %}
<html>
  <head>
    <title>My Lame Imgur</title>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>

    {% block extrahead %}
    {% endblock %}

    <link rel="stylesheet" type="text/css" href="{% static 'app/css/app.css' %}">
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">My Lame Imgur</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">Hi {{user.username}}</a>
            </li>
            {%if user.is_superuser%}
            <li class="nav-item">
              <a class="nav-link" href="/admin">Admin dashboard</a>
            </li>
            {%endif%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout'%}">Logout</a>
            </li>
            {%else%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup'%}">Register</a>
            </li>
            {% endif %}

          </ul>
        </div>
      </nav>

    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron">
            <div class="container">
              <h1 class="display-4">My Lame Imgur</h1>
              <p class="lead">Your one stop place for posting your lamest images!</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 mb-2">
            {% block profile_username %}
            {% endblock %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-6">
          {% block account_comments %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>